# Generated by Django 5.1.3 on 2025-03-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolistapp", "0002_taskers"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tasker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="todolistapp.taskers",
            ),
        ),
    ]
